// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD1FEWZg7PS9N_AsptQb4NHA1oG5USB_4',
    appId: '1:488930574454:web:7ecf6bef48a0f300bddf57',
    messagingSenderId: '488930574454',
    projectId: 'unipath-nasc',
    authDomain: 'unipath-nasc.firebaseapp.com',
    storageBucket: 'unipath-nasc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE3L4KzPEDoXxmFHhsEcm9uNobZGyillU',
    appId: '1:488930574454:android:3c3b16792fc095f1bddf57',
    messagingSenderId: '488930574454',
    projectId: 'unipath-nasc',
    storageBucket: 'unipath-nasc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN5t_4eTvPzXXBeGChejATjS2n5MBDzVk',
    appId: '1:488930574454:ios:2faa38abde5c34ecbddf57',
    messagingSenderId: '488930574454',
    projectId: 'unipath-nasc',
    storageBucket: 'unipath-nasc.firebasestorage.app',
    iosBundleId: 'com.example.unipath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN5t_4eTvPzXXBeGChejATjS2n5MBDzVk',
    appId: '1:488930574454:ios:2faa38abde5c34ecbddf57',
    messagingSenderId: '488930574454',
    projectId: 'unipath-nasc',
    storageBucket: 'unipath-nasc.firebasestorage.app',
    iosBundleId: 'com.example.unipath',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD1FEWZg7PS9N_AsptQb4NHA1oG5USB_4',
    appId: '1:488930574454:web:d52edbe3ea790141bddf57',
    messagingSenderId: '488930574454',
    projectId: 'unipath-nasc',
    authDomain: 'unipath-nasc.firebaseapp.com',
    storageBucket: 'unipath-nasc.firebasestorage.app',
  );
}
